# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 13:19
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=80)),
                ('albumTitle', models.CharField(max_length=250)),
                ('genre', models.CharField(max_length=40)),
                ('albumLogo', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileType', models.CharField(max_length=10)),
                ('songTitle', models.CharField(max_length=250)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userProfile.Album')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=16)),
                ('fullName', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=32)),
                ('adress', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=14)),
                ('userPhoto', models.CharField(max_length=1000)),
            ],
        ),
    ]
